apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: website-deployment
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: website-deployment
    spec:
      containers:      
      - image: masihtech/ecom-web:v6
        name: ecom-web
        env:
        # Define the environment variable
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: dbconfig
              # Specify the key associated with the value
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: dbconfig
              # Specify the key associated with the value
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: dbconfig
              # Specify the key associated with the value
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: dbconfig
              # Specify the key associated with the value
              key: DB_NAME
        resources: {}
status: {}
