FROM mariadb 

COPY . /docker-entrypoint-initdb.d

ENV MARIADB_ROOT_PASSWORD=my-secret-pw
ENV MARIADB_USER=example-user
ENV MARIADB_PASSWORD=my_cool_secret
ENV MARIADB_DATABASE=ecomdb
ENV MARIADB_ROOT_PASSWORD=my-secret-pw
